# Generated by Django 5.2.2 on 2025-06-06 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_assignment_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='approval_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='status',
            field=models.CharField(choices=[('pending', 'În așteptare'), ('approved', 'Aprobată'), ('rejected', 'Respinsă')], default='pending', max_length=10),
        ),
    ]
